import type { Metadata } from "next";
import localFont from "next/font/local";
import { Pacifico } from 'next/font/google';
import { Pangolin  } from 'next/font/google';
import "./globals.css";

const pacifico = Pacifico({
  subsets: ['latin'],
  weight: '400', 
  variable: '--font-pacifico', // optional CSS variable
});
const pangolin = Pangolin({
  subsets: ['latin'],
  weight: '400', 
  variable: '--font-pangolin', // optional CSS variable
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pangolin.className}`}
      >
        {children}
      </body>
    </html>
  );
}
